### ISSUE TITLE
Use spritewidget package from pub.dartlang instead of local copy

### ISSUE THREAD

**Issue by raju-bitter** [spritewidget/spaceblast#1]
pubspec.yaml uses a path setting for the spritewidget package:
```
dependencies:
  flutter:
    sdk: flutter
  spritewidget:
    path: ../spritewidget
```
Instead the package from dartlang.org should be used:
https://pub.dartlang.org/packages/spritewidget
